# Generated by Django 2.0.2 on 2019-06-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20190604_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=' ', upload_to='teacher/%Y%m', verbose_name='头像'),
        ),
    ]
