# Generated by Django 2.0.2 on 2019-05-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='add_tiem',
            new_name='add_time',
        ),
    ]
