# Generated by Django 2.0.2 on 2019-06-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='后端开发', max_length=10, verbose_name='课程类别'),
        ),
    ]
