# Generated by Django 2.0.2 on 2019-06-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190610_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='老师提醒'),
        ),
        migrations.AlterField(
            model_name='course',
            name='youneed_known',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='课程须知'),
        ),
    ]
