# Generated by Django 2.0.2 on 2019-06-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20190610_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='course/vedio/%Y/%m', verbose_name='访问地址'),
        ),
    ]
