# Generated by Django 2.0.2 on 2019-06-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190610_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(upload_to='http://127.0.0.1:8000/media/course/resource/%Y/%m', verbose_name='下载'),
        ),
    ]
